---
title: "RWorksheet_Barrientos#3b.Rmd"
author: "Auderie Josh Barrientos"
date: "2024-10-13"
output: pdf_document
---

1.  
A.  

```{r}
data <- data.frame(
  Respondents = 1:20,
  Sex = c(2, 1, 2, 2, 1, 1, 2, 2, 2, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 2),
  FatherOccupation = c(1, 2, 3, 1, 2, 1, 3, 2, 3, 3, 1, 3, 2, 1, 3, 1, 3, 3, 1, 1),
  Persons_at_Home = c(5, 7, 3, 5, 5, 3, 6, 6, 7, 7, 3, 7, 4, 7, 8, 8, 3, 11, 8, 6),
  Siblings_at_School = c(6, 4, 3, 2, 3, 3, 5, 5, 4, 5, 3, 7, 5, 2, 1, 3, 1, 5, 3, 2),
  Types_of_Houses = c(1, 2, 3, 1, 3, 1, 3, 3, 3, 1, 3, 3, 3, 1, 3, 3, 3, 3, 3, 2)
)
data
```

B.  

```{r}
str(data)
summary(data)
```

C.  

```{r}
mean(data$Siblings_at_School)
```

D.  

```{r}
data[1:2, ]
```

E.  

```{r}
data[c(3, 5), c(2, 4)]
```

F.  

```{r}
types_houses <- data$Types_of_Houses
types_houses
```

G.  

```{r}
Male_Farmers <- subset(data, Sex == 1 & FatherOccupation == 1)
Male_Farmers
```

H.  

```{r}
Female_Siblings <- subset(data, Sex == 2 & Siblings_at_School >= 5)
Female_Siblings
```

2.  
A.  

```{r}
df = data.frame(Ints=integer(),

Doubles=double(), Characters=character(),
Logicals=logical(),
Factors=factor(),
stringsAsFactors=FALSE)

print("Structure of the empty dataframe:")
print(str(df))
```

3.  
A.  

```{r}
datac <- read.csv("HouseholdData.csv")
datac
```

B.  

```{r}
datac$Sex <- factor(datac$Sex, levels = c("Male", "Female"), labels = c(1,2))
datac
```

C.  

```{r}
datac$TypesOfHouses <- factor(datac$TypesOfHouses, levels = c("Wood", "Congrete", "Semi-congrete"), labels = c(1,2,3))
datac

```

D.  

```{r}
datac$FathersOccupation <- factor(datac$FathersOccupation, levels = c(1,2,3), labels = c("Farmer", "Driver", "Others"))
datac
```

E.  

```{r}
FemaleDriverDad <- subset(datac, Sex == 2 & FathersOccupation =="Driver")
FemaleDriverDad
```

F.  

```{r}
manysiblings <- subset(datac, Respondents & SiblingsAtSchool >= 5)
manysiblings
```

4.  The graph shows thw Sentiments Of Tweets Per Day, from July 14, 2020 to July 21, 2020.The red shows negative, orange shows neutral, and blue shows a positive.As the graph shows that the negative tweets is the highest of the all.
