---
title: "RWorksheet_Barrientos#ARmn.Rmd"
author: "Auderie Josh Barrientos"
date: "2024-10-11"
output:
  pdf_document: default
  word_document: default
---



1.
a.
```{r}
Letters <- c("A","B","C","D","E","F","G","H","I","J","K","L","M","N", "O","P","Q","R","S","T","U","V","W","X","Y","Z")

letters <- c("a","b","c","d","e","f","g","h","i","j","k","l","m","n", "o","p","q","r","s","t","u","v","w","x","y","z")
```

```{r}
eleven <- Letters[1:11]
eleven
```

b.
```{r}
odd <- Letters[seq("1","26", by = 2)]
odd
```

c.
```{r}
vowels <- Letters[c(1,5,9,15,21)]
vowels
```
d.
```{r}
last5 <- tail(letters,5)
last5
```
e.
```{r}
between <- letters[c(15:24)]
between
```
2.

```{r}

tempp <- c(42,39,34,34,30,27)
```
a.
```{r}

place <- c("Tuguegarao City", "Manila", "Iloilo City", "Tacloban","Samal Island", "Davao City")
```
b.
```{r}

temp <- mean(tempp)
temp
```
c.
```{r}

city_temp <- data.frame(tempp,place)
city_temp
```

d.
```{r}
names(city_temp) <-  c("Temperature", "City") 
city_temp
```
e.
```{r}

str(city_temp)
```


f.
```{r}

row_content3 <- city_temp[3,]
row_content4 <- city_temp[4,]

row_content3
row_content4

```

g.
```{r}

max_index <- max(city_temp$Temperature)
max_index

min_index <- min(city_temp$Temperature)
min_index
```
2.
```{r}

matrics <- matrix(c(1:8,11:14),nrow=3,ncol=4)
matrics
```

b.
```{r}

multiply <- matrics*2
multiply
```
c.
```{r}

row2 <- matrics[2,]
row2
```

d.
```{r}

display <-  matrics[1:2,3:4]
display
```

e.
```{r}

col23 <- matrics[3,2:3]
col23

```

f.
```{r}
col4 <- matrics[,4]
col4

```
g.
```{r}
dimnames(multiply) <- list( c("isa", "dalawa", "tatlo"),  c("uno", "dos", "tres", "quatro"))
multiply
```

h.
```{r}
dim(matrics) <- c(6,2)
matrics
```
3.

```{r}
arr <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)
arr
rra <- c(1, 2, 3, 6, 7, 8, 9, 0, 3, 4, 5, 1)
rra
```
a.


```{r}
aray <- array(c(arr,rra),dim=c(2,4,3))
 aray
```
b.

3.

C.
```{r}
column.names <- c("A","B","C","D")
row.names <- c("a","b")
matrix.names <- c("1st-Dimensional Array","2nd-Dimensional Array","3rd-Dimensional Array")

aray <- array(c(arr,rra),dim = c(2,4,3),dimnames = list(row.names,column.names,
   matrix.names))
aray
```
