---
title: "Worksheet4a"
author: "Auderie Josh Barrientos"
date: "2024-10-15"
output: pdf_document
---

#1.
#a.
```{r}
Data <- c(Household_Data)
Data
```
#b.
```{r}
data <- data.frame(
  Shoe_size = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 8.5, 12.0, 10.5),
  Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 71.0, 72.0, 72.0, 64.0, 72.0, 67.0, 71.0, 71.0, 71.0),
  Gender = c("F", "F", "F", "F", "M", "M", "M", "M", "M", "F", "M", "F", "M", "M", "M")
)

FemaleData <- subset(data, Gender == "F", select = c(Shoe_size, Height))
FemaleData
MaleData <- subset(data, Gender == "M", select = c(Shoe_size, Height))
MaleData
```
#c.
```{r}
data <- data.frame(
  Shoe_size = c(6.5, 9.0, 8.5, 8.5, 10.5, 7.0, 9.5, 9.0, 13.0, 7.5, 10.5, 8.5, 8.5, 12.0, 10.5),
  Height = c(66.0, 68.0, 64.5, 65.0, 70.0, 64.0, 71.0, 72.0, 72.0, 64.0, 72.0, 67.0, 71.0, 71.0, 71.0),
  Gender = c("F", "F", "F", "F", "M", "M", "M", "M", "M", "F", "M", "F", "M", "M", "M")
)

mean_shoe_size <- mean(data$Shoe_size)
mean_shoe_size
mean_height <- mean(data$Height)
mean_height
```
#d.
Yes beacuase the bigger the person is the bigger it's shoe size and ofcourse it is more likely to men.

#2.
```{r}
months <- c("March","April","January","November","January",
          "September","October","September","November","August",
          "January","November","November","February","May","August",
          "July","December","August","August","September","November",
          "February","April")

factor_months_vector <- factor(months)
factor_months_vector
```
#3.
```{r}
# Create a character vector of months
months_vector <- c("March","April","January","November","January",
          "September","October","September","November","August",
          "January","November","November","February","May","August",
          "July","December","August","August","September","November",
          "February","April")


factor_months_vector <- factor(months_vector)
factor_months_vector

summary(months_vector)
summary(factor_months_vector)

```
4.




